#!/bin/bash

# Check root
if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (sudo)" >&2
  exit 1
fi

echo "Installing ChameleonGRUB..."

# Install dependencies
echo "→ Installing dependencies..."
if command -v apt-get &> /dev/null; then
  apt-get install -y curl unzip sed grub2-common zenity
elif command -v pacman &> /dev/null; then
  pacman -S --noconfirm curl unzip sed grub zenity
fi

# Copy themes
echo "→ Installing themes..."
mkdir -p /usr/share/grub/themes/
cp -r themes/* /usr/share/grub/themes/

# Install main script
echo "→ Installing main script..."
install -Dm755 ChameleonGRUB /usr/local/bin/ChameleonGRUB

# Create config dir
mkdir -p /etc/ChameleonGRUB/
[ ! -f /etc/ChameleonGRUB/exclude.conf ] && 
  cp exclude.conf.example /etc/ChameleonGRUB/exclude.conf

# Kali Linux special config
if [ -d "/etc/default/grub.d" ]; then
  echo "→ Configuring Kali Linux GRUB..."
  cat > /etc/default/grub.d/kali-themes.cfg << 'EOF'
# Auto-generated by ChameleonGRUB
GRUB_THEME="/usr/share/grub/themes/%THEME%/theme.txt"
EOF
  sed -i 's|%THEME%|'"$(basename "$(find /usr/share/grub/themes/ -mindepth 1 -maxdepth 1 -type d | shuf -n 1)")"'|' /etc/default/grub.d/kali-themes.cfg
fi

# Systemd service
echo "→ Setting up systemd service..."
cat > /etc/systemd/system/ChameleonGRUB.service <<EOF
[Unit]
Description=ChameleonGRUB - Dynamic GRUB Theme Switcher
Before=grub-update.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ChameleonGRUB

[Install]
WantedBy=sysinit.target
EOF

systemctl daemon-reload
systemctl enable ChameleonGRUB.service

# First run
echo "→ Applying initial theme..."
/usr/local/bin/ChameleonGRUB

echo -e "\n✅ ChameleonGRUB successfully installed!\nThemes will rotate on every reboot."
echo "Try these commands:"
echo "  sudo ChameleonGRUB --preview   # Preview next theme"
echo "  sudo ChameleonGRUB --list      # Show available themes"
